# This is a basic workflow that is manually triggered

name: Manual workflow

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:
    # Inputs the workflow accepts.
    

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "greet"
  commit_log:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Runs a single command using the runners shell
    - uses: actions/checkout@v2
      with:
        fetch-depth: 10
    - name: Logging
      run: |
        echo 'NOTE<<EOF' >> $GITHUB_ENV
        git log -10 >> $GITHUB_ENV
        echo 'EOF' >> $GITHUB_ENV
    - name: output
      run: |
        echo "this is release note"
        echo "${{env.NOTE}}"
        
